/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:221725:
  
  if(event == GEvent.PRESSED){
    println("Clicked forward button");
    if(zumoGUI.manual_mode){
      // Send move forward to zumo until button is released
      zumoGUI.serialPort.write(2);
    }
    else{
      // Activate task 2 if zumo is autonomous
      zumoGUI.serialPort.write(7);
    }
  }
  if(event == GEvent.RELEASED || event == GEvent.CLICKED){
    println("Released forward button");
    if(zumoGUI.manual_mode){
      // Tell zumo to stop
      zumoGUI.serialPort.write(1);
    }
  }
  
} //_CODE_:button1:221725:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:819618:
  
  if(event == GEvent.PRESSED){
    println("Clicked backward button");
    if(zumoGUI.manual_mode){
      // Send move backward to zumo until button is released
      zumoGUI.serialPort.write(3);
    }
    else{
      // Do nothing for now
      // Maybe disable this buttons in autonomous
    }
  }
  if(event == GEvent.RELEASED || event == GEvent.CLICKED){
    println("Released backward button");
    if(zumoGUI.manual_mode){
      // Tell zumo to stop
      zumoGUI.serialPort.write(1);
    }
  }
  
} //_CODE_:button2:819618:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:590894:
  
  if(event == GEvent.PRESSED){
    println("Clicked left button");
    if(zumoGUI.manual_mode){
      // Send turn left to zumo until button is released
      zumoGUI.serialPort.write(4);
    }
    else{
      // Do nothing for now
      // Maybe disable this buttons in autonomous
    }
  }
  if(event == GEvent.RELEASED || event == GEvent.CLICKED){
    println("Released left button");
    if(zumoGUI.manual_mode){
      // Tell zumo to stop
      zumoGUI.serialPort.write(1);
    }
  }
  
} //_CODE_:button3:590894:

public void button4_click1(GButton source, GEvent event) { //_CODE_:button4:761249:
    
  if(event == GEvent.PRESSED){
    println("Clicked right button");
    if(zumoGUI.manual_mode){
      // Send turn right to zumo until button is released
      zumoGUI.serialPort.write(5);
    }
    else{
      // Do nothing for now
      // Maybe disable this buttons in autonomous
    }
  }
  if(event == GEvent.RELEASED || event == GEvent.CLICKED){
    println("Released right button");
    if(zumoGUI.manual_mode){
      // Tell zumo to stop
      zumoGUI.serialPort.write(1);
    }
  }
  
} //_CODE_:button4:761249:

public void textarea1_change1(GTextArea source, GEvent event) { //_CODE_:textarea1:657745:
  println("textarea1 - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:textarea1:657745:

public void imgTogButton1_click1(GImageToggleButton source, GEvent event) { //_CODE_:imgTogButton1:529271:
  
  // Indicate the zumo to change its behavior
  //zumoGUI.serialPort.write(6);
  
  if(imgTogButton1.getState() == 0){
    label1.setText("Manual mode");
    println("Zumo changed to manual mode");
    zumoGUI.manual_mode = true;
    // Enable usable buttons
    button2.setEnabled(true);
    button3.setEnabled(true);
    button4.setEnabled(true);
  }
  else{
    label1.setText("Autonomous mode");
    println("Zumo changed to autonomous mode");
    zumoGUI.manual_mode = false;
    // Disable not usable buttons
    button2.setEnabled(false);
    button3.setEnabled(false);
    button4.setEnabled(false);
  }
  
} //_CODE_:imgTogButton1:529271:

public void textarea2_change1(GTextArea source, GEvent event) { //_CODE_:textarea2:444045:
  println("textarea2 - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:textarea2:444045:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Zumo Rescue GUI");
  button1 = new GButton(this, 300, 212, 80, 30);
  button1.setText("Forward");
  button1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button1.fireAllEvents(true);
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, 300, 280, 80, 30);
  button2.setText("Backward");
  button2.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button2.fireAllEvents(true);
  button2.addEventHandler(this, "button2_click1");
  button3 = new GButton(this, 215, 246, 80, 30);
  button3.setText("Turn Left");
  button3.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button3.fireAllEvents(true);
  button3.addEventHandler(this, "button3_click1");
  button4 = new GButton(this, 385, 246, 80, 30);
  button4.setText("Turn Right");
  button4.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button4.fireAllEvents(true);
  button4.addEventHandler(this, "button4_click1");
  textarea1 = new GTextArea(this, 6, 24, 200, 150, G4P.SCROLLBARS_NONE);
  textarea1.setOpaque(true);
  textarea1.addEventHandler(this, "textarea1_change1");
  imgTogButton1 = new GImageToggleButton(this, 321, 25);
  imgTogButton1.addEventHandler(this, "imgTogButton1_click1");
  label1 = new GLabel(this, 280, 80, 120, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Manual mode");
  label1.setOpaque(false);
  label2 = new GLabel(this, 6, 2, 100, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Zumo messages");
  label2.setOpaque(false);
  label3 = new GLabel(this, 240, 130, 200, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Current performing: Task 1");
  label3.setOpaque(true);
  label4 = new GLabel(this, 6, 188, 80, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("GUI help");
  label4.setOpaque(false);
  textarea2 = new GTextArea(this, 6, 212, 200, 100, G4P.SCROLLBARS_NONE);
  textarea2.setOpaque(true);
  textarea2.addEventHandler(this, "textarea2_change1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GButton button2; 
GButton button3; 
GButton button4; 
GTextArea textarea1; 
GImageToggleButton imgTogButton1; 
GLabel label1; 
GLabel label2; 
GLabel label3; 
GLabel label4; 
GTextArea textarea2; 
