/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void forwardButtonClick(GButton source, GEvent event) { //_CODE_:forward_button:221725:
  
  forwardButton(event);
  
} //_CODE_:forward_button:221725:

public void backwardButtonClick(GButton source, GEvent event) { //_CODE_:backward_button:819618:
  
  backwardButton(event);
  
} //_CODE_:backward_button:819618:

public void leftButtonClick(GButton source, GEvent event) { //_CODE_:left_button:590894:
  
  leftButton(event);
  
} //_CODE_:left_button:590894:

public void rightButtonClick(GButton source, GEvent event) { //_CODE_:right_button:761249:
    
  rightButton(event);
  
} //_CODE_:right_button:761249:

public void modeToggleClick(GImageToggleButton source, GEvent event) { //_CODE_:mode_toggle:529271:
  
  modeToggleButton();
  
} //_CODE_:mode_toggle:529271:

public void roomButtonClick(GButton source, GEvent event) { //_CODE_:room_button:437079:
  
  
  
} //_CODE_:room_button:437079:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  forward_button = new GButton(this, 300, 212, 80, 30);
  forward_button.setText("Forward");
  forward_button.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  forward_button.addEventHandler(this, "forwardButtonClick");
  backward_button = new GButton(this, 300, 280, 80, 30);
  backward_button.setText("Backward");
  backward_button.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  backward_button.addEventHandler(this, "backwardButtonClick");
  left_button = new GButton(this, 215, 246, 80, 30);
  left_button.setText("Turn Left");
  left_button.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  left_button.addEventHandler(this, "leftButtonClick");
  right_button = new GButton(this, 385, 246, 80, 30);
  right_button.setText("Turn Right");
  right_button.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  right_button.addEventHandler(this, "rightButtonClick");
  mode_toggle = new GImageToggleButton(this, 321, 25);
  mode_toggle.addEventHandler(this, "modeToggleClick");
  mode_label = new GLabel(this, 280, 80, 120, 20);
  mode_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  mode_label.setText("Manual mode");
  mode_label.setOpaque(false);
  zumo_msg_label = new GLabel(this, 6, 2, 100, 20);
  zumo_msg_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  zumo_msg_label.setText("Zumo messages");
  zumo_msg_label.setOpaque(false);
  current_task_label = new GLabel(this, 240, 120, 200, 20);
  current_task_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  current_task_label.setText("Current performing: Task 1");
  current_task_label.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  current_task_label.setOpaque(true);
  gui_help_label = new GLabel(this, 6, 160, 80, 20);
  gui_help_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  gui_help_label.setText("GUI help");
  gui_help_label.setOpaque(false);
  zumo_msg_fill_label = new GLabel(this, 6, 24, 200, 120);
  zumo_msg_fill_label.setTextAlign(GAlign.LEFT, GAlign.TOP);
  zumo_msg_fill_label.setOpaque(true);
  gui_help_fill_label = new GLabel(this, 6, 182, 200, 150);
  gui_help_fill_label.setTextAlign(GAlign.LEFT, GAlign.TOP);
  gui_help_fill_label.setOpaque(true);
  room_button = new GButton(this, 300, 150, 80, 30);
  room_button.setText("Room!");
  room_button.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  room_button.addEventHandler(this, "roomButtonClick");
}

// Variable declarations 
// autogenerated do not edit
static GButton forward_button; 
static GButton backward_button; 
static GButton left_button; 
static GButton right_button; 
static GImageToggleButton mode_toggle; 
static GLabel mode_label; 
static GLabel zumo_msg_label; 
static GLabel current_task_label; 
static GLabel gui_help_label; 
static GLabel zumo_msg_fill_label; 
static GLabel gui_help_fill_label; 
static GButton room_button; 
